### ISSUE TITLE
OCRTesseract post processing image

### ISSUE THREAD

**Issue by artursharykin** [artursharykin/Overwatch-2-Screenshot-OCR-Tool#7]
For better OCR recognition, there should be a couple more methods to make the OCR recognition more accurate, this would be something that needs a lot of testing and work.

**Comment by ALEEF02** [comment]
Addressed in https://github.com/wsnek/Overwatch-2-Screenshot-OCR-Tool/commit/8e22a2c49403c0d0449e4e551a9b77d7468b6352 and https://github.com/wsnek/Overwatch-2-Screenshot-OCR-Tool/commit/301e69ce996a496c027c9bf73ef51563dfea99e5.
